name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Debug Verify Project ID
        run: |
          if [ -z "${{ secrets.GCLOUD_PROJECT }}" ]; then
            echo "❌ ERROR: GCLOUD_PROJECT secret is empty!"
            exit 1
          fi
          echo "✅ Using Project ID: ${{ secrets.GCLOUD_PROJECT }}"

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/semantic-search/semantic-search:latest .

      - name: Configure Docker auth for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Push to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/semantic-search/semantic-search:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy semantic-search \
            --image us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/semantic-search/semantic-search:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --quiet
